sudo: true
service: docker
language: ruby
cache:
- bundler
before_install:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always

before_script:
  - docker run --name sensu-debian-stretch -d debian:stretch-slim; apt install default-libmysqlclient-dev  -y
  - docker ps -a
  - bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone' ; cp asset_build_scripts/Dockerfile.* bonsai/ruby-runtime/"
    
script:
- bundle exec rake quick
#- bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
- gem build sensu-plugins-percona.gemspec
- gem install sensu-plugins-percona-*.gem
deploy:
  - provider: script
    script: chmod +x bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh && bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-percona
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      rvm: 2.4.1
  - provider: rubygems
    api_key:
      secure: B5Q6RCwDLexIBKW5UZQ8pGeIiq9zVtourg2qf2UbgeUgDRhyZGNf0s/XE8aBh5ZNqFAJQRl0KzDV4XHjcQqD31up8+MiEy3cqTP+Hxn6w2aHbqjwccrIzCk+jQus5nk+alkUAwLeGJkI8IFSeLfBtRpabigqQN0jdMo0NCPg5kM=
    gem: sensu-plugins-percona
    on:
      tags: true
      all_branches: true
      rvm: 2.4.1
      repo: sensu-plugins/sensu-plugins-percona